version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: app.development.dockerfile
    links:
      - db
    volumes:
      - build:/app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: "development"
      MONGO_HOST: "db"
  db:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"

volumes:
  build:
