version: "3.1"
services:
  builder:
    build: ../fullstack-build
    command: [./build]
    environment:
      FULLSTACK_CONFIG: "${PWD}/fullstack.config.js"
    volumes:
      - "${PWD}:${PWD}"
  cleaner:
    build: ../fullstack-build
    command: [./clean]
    environment:
      FULLSTACK_CONFIG: "${PWD}/fullstack.config.js"
    volumes:
      - "${PWD}:${PWD}"
  watcher:
    build: ../fullstack-build
    command: [./watch]
    environment:
      # Where to find the config file in the container
      # TODO: make this a command parameter
      FULLSTACK_CONFIG: "${PWD}/fullstack.config.js"
    volumes:
      - "${PWD}:${PWD}"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "35729:35729"
