version: "3.1"

services:
  # Development app.
  # Mimic production Dockerfile.
  app:
    image: node:7.5.0
    links:
      - db
    volumes:
      # relative to the host or host-VM
      - ./build:/build
      - ./server/node_modules:/build/server/node_modules
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: "development"
      MONGO_HOST: "db"
      PORT: "9000"
      APP_DOMAIN: "${APP_DOMAIN}"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
    expose:
      - "9000"
    command: node /build/server

  # Database for development app
  db:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"

  # Install server packages
  npm-server:
    image: node:7.5.0
    volumes:
      - ./server:/dir
    working_dir: /dir
    entrypoint: npm
    command: install

  # Install client packages
  npm-client:
    image: node:7.5.0
    volumes:
      - ./client:/dir
    working_dir: /dir
    entrypoint: npm
    command: install
