version: "3.1"
services:
  builder:
    build: ../fullstack-build
    command: [./build]
    volumes:
      - .:/src
      - build:/build
      - ./fullstack.config.js:/fullstack.config.js
  cleaner:
    build: ../fullstack-build
    command: [./clean]
    volumes:
      - build:/build
      - ./fullstack.config.js:/fullstack.config.js
  watcher:
    build: ../fullstack-build
    command: [./watch]
    volumes:
      - .:/src
      - build:/build
      - ./fullstack.config.js:/fullstack.config.js
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "35729:35729"

volumes:
  # Volume for holding built code
  build:
