version: "3.1"
services:
  builder:
    build: ../fullstack-build
    command: [./build]
    environment:
      FULLSTACK_CONFIG: "${PWD}/fullstack.config.js"
    volumes:
      - "${PWD}:${PWD}"
  cleaner:
    build: ../fullstack-build
    command: [./clean]
    environment:
      FULLSTACK_CONFIG: "${PWD}/fullstack.config.js"
    volumes:
      - "${PWD}:${PWD}"
  watcher:
    build: ../fullstack-build
    command: [./watch]
    environment:
      APP_DOMAIN: "${APP_DOMAIN}"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
      OFFLINE_USER: "${OFFLINE_USER}"
      OFFLINE_USER_NAME: "${OFFLINE_USER_NAME}"
      OFFLINE_USER_PERMISSIONS: "${OFFLINE_USER_PERMISSIONS}"
      # Where to find the config file in the container
      # TODO: make this a command parameter
      FULLSTACK_CONFIG: "${PWD}/fullstack.config.js"
    volumes:
      - "${PWD}:${PWD}"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "35729:35729"
