version: "3.1"
services:
  builder:
    build: ../fullstack-build
    command: [./build]
    volumes:
      - ./client:/client
      - ./resources:/resources
      - ./server:/server
      - ./.git:/.git
      - ./build:/build
      - ./fullstack.config.js:/fullstack.config.js
  cleaner:
    build: ../fullstack-build
    command: [./clean]
    volumes:
      - ./build:/build
      - ./fullstack.config.js:/fullstack.config.js
  watcher:
    build: ../fullstack-build
    command: [./watch]
    volumes:
      - ./client:/client
      - ./resources:/resources
      - ./server:/server
      - ./.git:/.git
      - ./build:/build
      - ./fullstack.config.js:/fullstack.config.js
      # For running app in a container
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/docker-compose.yml
      - ./app.development.dockerfile:/app.development.dockerfile
    ports:
      - "35729:35729"
