version: "3.1"
services:
  # Development app.
  app:
    build:
      context: .
      dockerfile: app.development.dockerfile
    links:
      - db
    volumes:
      - build:/app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: "development"
      MONGO_HOST: "db"

  db:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"

  install-server:
    image: node:7.5.0
    volumes:
      - ./server/package.json:/package.json
      - ./server/node_modules:/node_modules
    environment:
      NODE_ENV: production
    command: npm install

  install-client:
    image: node:7.5.0
    volumes:
      - ./client/package.json:/package.json
      - ./client/node_modules:/node_modules
    environment:
      NODE_ENV: production
    command: npm install

volumes:
  build:
