#!/usr/bin/env bash

# NPM for top-level node modules.
# Running npm as root sets unsafe-perm to false; set it back to true.

docker pull gomoto/node-docker-compose

docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(pwd):$(pwd) \
  --workdir=$(pwd) \
  --interactive \
  --tty \
  --rm \
  gomoto/node-docker-compose \
  npm --unsafe-perm "$@"
