#!/usr/bin/env bash

# Node image should match Dockerfile base image.
docker pull node:7.5.0

# NPM for server modules.
# Running npm as root sets unsafe-perm to false; set it back to true.
docker run \
  -v $(pwd):$(pwd) \
  --workdir=$(pwd)/server \
  --interactive \
  --tty \
  --rm \
  node:7.5.0 \
  npm --unsafe-perm "$@"
